### ISSUE TITLE
PHP Strict Standards

### ISSUE THREAD

**Issue by WebNashr** [TwoBeers/fastfood#27]
I get the following:
PHP Strict Standards:  Redefining already defined constructor for class Fastfood_Comment_Reply in /home/webnashr/public_html/wp-content/themes/fastfood/lib/comment-reply.php on line 26

**Comment by jimo** [comment]
Sorry for the late reply.
Fastfood (like Shiword) was created 2 years ago. Newer version of PHP (5.6+) added some new standards and new error reporting. No worries at all, the theme still works. In future release we'll manage those notices
